#!/bin/bash -e

DIR=$HOME/dev/foreman-packaging

ACTION=$1
if [[ -z $ACTION ]] ; then
	echo "Usage: $0 ACTION"
	exit 1
fi
shift

pick() {
	VERSION=$1
	COMMIT=$2

	if [[ -z $VERSION ]] || [[ -z $COMMIT ]]; then
		echo "Usage: $0 cherry-pick VERSION COMMIT"
		exit 1
	fi

	COMMIT=$(git rev-parse $COMMIT)

	git checkout rpm/$VERSION
	git pull
	git cherry-pick $COMMIT
}

changed() {
	git --git-dir $DIR/.git show --pretty="format:" --name-only $1 | grep .spec | xargs --no-run-if-empty dirname | sort -u | sed "s|^|$DIR/|"
}

sources() {
	$DIR/setup_sources.sh .
}

get_build() {
	rpmspec --srpm -q --define 'dist .el7' --queryformat "%{name}-%{version}-%{release}\n" "$@"
}

get_tfm_build() {
	get_build --define 'scl tfm' "$@"
}

if [[ $ACTION == "pick" ]] ; then
	pick "$@"
elif [[ $ACTION == "release-changed" ]] ; then
	changed $1 | xargs -n 1 basename | xargs obal release
	#-e build_package_wait=False
elif [[ $ACTION == "changed" ]] ; then
	changed $1
elif [[ $ACTION == "sources" ]] ; then
	sources
elif [[ $ACTION == "get-build" ]] ; then
	for dir in "$@" ; do
		get_build $dir/*.spec
	done
elif [[ $ACTION == "get-tfm-build" ]] ; then
	for dir in "$@" ; do
		get_tfm_build $dir/*.spec
	done
else
	echo "Usage: $0 ACTION"
	exit 1
fi
