#!/bin/bash -e

BASE_DIR=$HOME/dev
PACKAGING_DIR=$BASE_DIR/foreman-packaging

if [[ "$1" != "remote_execution" ]] && [[ "$1" != "ansible" ]] && [[ "$1" != "tasks" ]]; then
	echo "Usage: $0 [remote_execution|ansible|tasks]"
	exit 1
fi

if [[ "$1" == "tasks" ]] ; then
	PACKAGE="rubygem-foreman-$1"
else
	PACKAGE="rubygem-foreman_$1"
fi
BRANCH=rpm/${2:-develop}
LOCAL_BRANCH="${BRANCH}-bump-${PACKAGE}"
REMOTE="origin"
MESSAGE="Rebuild ${PACKAGE} for webpack"
SPEC_FILE="${PACKAGING_DIR}/packages/plugins/${PACKAGE}/${PACKAGE}.spec"

cd $PACKAGING_DIR
git fetch "$REMOTE"
if git branch | grep -q "\b${LOCAL_BRANCH}\b" ; then
	echo "Branch $LOCAL_BRANCH already exists"
	exit 1
fi

git checkout -b "${LOCAL_BRANCH}" "${REMOTE}/${BRANCH}"
obal bump-release "$PACKAGE" --changelog "- $MESSAGE"
git add "$SPEC_FILE"
git commit -m "$MESSAGE"
git phr -b "$BRANCH" -m "$MESSAGE"
